### ISSUE TITLE
Crash when adding cargo ships to an existing game

### ISSUE THREAD

**Issue by KiwiHawk** [rudegrass/cargo_ships#106]
![image](https://user-images.githubusercontent.com/59639/153701086-31d11cf7-306d-4cf7-8188-259482b50039.png)

Trying to add cargo ships to an existing Sea Block game (for testing)

**Comment by robot256** [comment]
Question: Do you have Deep Sea Oil disabled in startup settings?

**Comment by robot256** [comment]
Fixed in https://github.com/rudegrass/cargo_ships/pull/101/commits/839b226df4de692c8f9efe45ca67bc50f7539a4c 

Edit: And released in 0.1.16.  This can be closed.
