### ISSUE TITLE
Mod does not work with space exploration

### ISSUE THREAD

**Issue by Ectalite** [rudegrass/cargo_ships#107]
Deep oil cannot be placed when using Space exploration mod.

Log:   
`46.863 Script @__space-exploration__/prototypes/phase-3/resources.lua:24: Resource has no control: deep_oil                                                                                 46.863 Script @__space-exploration__/prototypes/phase-3/resources.lua:43: Resource cannot place: deep_oil`

**Comment by robot256** [comment]
This is operating correctly.  Deep oil gets placed by script when the map is generated, based on the auto-placed crude-oil deposits.  Please report a new issue if you see no deep oil on an ocean world with high oil probability.

**Comment by Ectalite** [comment]
Ok yes I discovered crude-oil deposits.
So it does work, thanks !
