### ISSUE TITLE
failed to load mods: Error with pump

### ISSUE THREAD

**Issue by theisen1337** [rudegrass/cargo_ships#115]
![image](https://github.com/squidy5/cargo_ships/assets/16194561/9dfd118b-1ea7-40f9-a2e2-91b0d651995f)

I noticed the error when loading my 100+ hr savefile:  

```
Error ModManager.cpp:1608: Error while running setup for entity prototype "pump" (pump): next_upgrade target (kr-steel-pump) must have the same collision mask.
```

When trying to load my save after update of cargo_ships. I am able to load the save without `cargo_ships` mod ( Don't receive error ).

## Expected Outcome:
Play my 100+ save file, with Cargo_ships.

## What Happens:
Game crashes when trying to load mod.

## Currently Work Around:
Deleting Cargo ships and discontinuing use of mod. ( None )

<details close></summary>Mods in save:<p></p> </summary>
 
  ["Advanced-Electric-Revamped-v16"] = "0.6.10",
  Aircraft = "1.8.6",
  AutoDeconstruct = "0.3.7",
  Bottleneck = "0.11.7",
  DiscoScience = "1.1.3",
  ["Electric Furnaces"] = "2.4.11",
  ElectricTrain = "1.1.2",
  Enhanced_Map_Colors = "1.5.5",
  ["Explosive Termites"] = "1.1.14",
  ["FARL-fixed-se"] = "4.1.3",
  FNEI = "0.4.1",
  Factorissimo2 = "2.5.3",
  ["Flare Stack"] = "2.2.10",
  ["Flow Control"] = "3.1.4",
  FluidMustFlow = "1.3.5",
  HelicopterRevival = "0.2.2",
  Howitzer = "0.3.1",
  Inserter_Config = "1.0.0",
  ["Invulnerable-Rails-and-Poles-continued"] = "110.0.1",
  Krastorio2 = "1.3.19",
  Krastorio2Assets = "1.2.1",
  Mining_Drones = "1.1.10",
  RPGsystem = "1.3.3",
  RampantArsenal = "1.1.6",
  Repair_Turret = "1.0.3",
  RitnLib = "0.7.7",
  Robocharger = "1.3.1",
  Robot_Battery_Research = "0.2.1",
  ["Shortcuts-ick"] = "1.1.28",
  SpidertronEnhancements = "1.8.16",
  ["Squeak Through"] = "1.8.2",
  StoneWaterWell = "1.20.1",
  StoneWaterWellAndSE = "1.0.0",
  Tapeline = "2.0.9",
  TaskList = "0.4.5",
  Transport_Drones = "1.0.14",
  Unit_Control = "0.3.11",
  VehicleSnap = "1.18.5",
  Warehousing = "0.5.7",
  ["aai-containers"] = "0.2.11",
  ["aai-industry"] = "0.5.19",
  ["aai-programmable-structures"] = "0.7.4",
  ["aai-programmable-vehicles"] = "0.7.24",
  ["aai-signal-transmission"] = "0.4.7",
  ["aai-signals"] = "0.6.1",
  ["aai-vehicles-chaingunner"] = "0.6.1",
  ["aai-vehicles-flame-tank"] = "0.5.1",
  ["aai-vehicles-flame-tumbler"] = "0.6.1",
  ["aai-vehicles-hauler"] = "0.6.1",
  ["aai-vehicles-laser-tank"] = "0.6.4",
  ["aai-vehicles-miner"] = "0.6.4",
  ["aai-vehicles-warden"] = "0.5.3",
  ["aai-zones"] = "0.6.4",
  ["alien-biomes"] = "0.6.8",
  ["alien-biomes-hr-terrain"] = "0.6.1",
  base = "1.1.80",
  ["belt-balancer-performance"] = "3.1.3",
  blueprint_flip_and_turn = "101.8.6",
  ["bullet-trails"] = "0.6.2",
  ["cargo-ships"] = "0.2.0",
  ["cargo-ships-graphics"] = "0.2.0",
  ["deep-storage-unit-se"] = "1.2.15",
  factoryplannerUnrestricted = "1.1.25",
  flib = "0.12.7",
  ["fluid-memory-storage-se"] = "1.3.17",
  ["grappling-gun"] = "0.3.3",
  informatron = "0.3.3",
  jetpack = "0.3.12",
  ["logistic-memory-units-se"] = "1.0.10",
  pump = "1.3.2",
  rampart_heavy_wall = "0.1.0",
  ["resourcehighlighter-dark"] = "2.5.0",
  robot_attrition = "0.5.15",
  robotarmy = "0.4.17",
  safefill = "1.0.11",
  scattergun_turret = "7.3.2",
  ["shield-generators"] = "0.3.5",
  ["shield-projector"] = "0.1.6",
  simhelper = "1.1.4",
  ["space-exploration"] = "0.6.105",
  ["space-exploration-graphics"] = "0.6.15",
  ["space-exploration-graphics-2"] = "0.6.1",
  ["space-exploration-graphics-3"] = "0.6.2",
  ["space-exploration-graphics-4"] = "0.6.2",
  ["space-exploration-graphics-5"] = "0.6.1",
  ["space-exploration-menu-simulations"] = "0.6.8",
  ["space-exploration-postprocess"] = "0.6.26",
  ["specialized-oil-processing"] = "1.4.3",
  ["spidertron-extended"] = "0.3.15",
  ["spidertron-logistics"] = "2.1.7"

</details>

**Comment by robot256** [comment]
Thanks for the report.  Please download the 0.2.1 hotfix.

**Comment by robot256** [comment]
For future reference, the workaround in a case like this is to download the previous working version of the mod from the mod portal and add it to the Factorio mods folder.  Then you can select which version to load in the in-game mod manager.

**Comment by theisen1337** [comment]
They Just updating, the hotfix seemed to fix the error, but upon game start I had to remove about 150 item recipes from the load. but haven't found any actual missing items.
