### ISSUE TITLE
Can't load my save anymore!

### ISSUE THREAD

**Issue by Fing3rz** [rudegrass/cargo_ships#12]
So I've been using the mod for a while now without any serious issues. Updated to 0.0.20 today, built some waterways, made a blueprint tile of a ship port setup i was working on, pasted the tile a few times, part of it may have overlapped a bit but it placed with a simple left-click(no shift, left-click). Then saved and closed my game. When I tried to load the save back up it crashes. here is the last bit of the crash log. i can upload the rest if you need.

`  33.792 Factorio initialised
  33.792 RivaTuner Statistics Server hook detected (rtsshooks64.dll)
  37.966 Loading map D:\Games\Factorio\saves\Moist.zip: 73960247 bytes.
  37.992 Loading Level.dat: 154057684 bytes.
  37.996 Info Scenario.cpp:136: Map version 0.16.51-0
Factorio crashed. Generating symbolized stacktrace, please wait ...
c:\cygwin64\tmp\factorio-build-gumsut\libraries\stackwalker\stackwalker.cpp (924): StackWalker::ShowCallstack
c:\cygwin64\tmp\factorio-build-gumsut\src\util\logger.cpp (408): Logger::writeStacktrace
c:\cygwin64\tmp\factorio-build-gumsut\src\util\logger.cpp (521): Logger::logStacktrace
c:\cygwin64\tmp\factorio-build-gumsut\src\util\logging.cpp (89): Logging::logAndAbortOrThrow
c:\cygwin64\tmp\factorio-build-gumsut\src\util\logging.cpp (83): Logging::logAndAbortOrThrow
c:\cygwin64\tmp\factorio-build-gumsut\src\rail\railsegment.cpp (150): RailSegment::initFrom
c:\cygwin64\tmp\factorio-build-gumsut\src\rail\trainmanager.cpp (103): TrainManager::setup
c:\cygwin64\tmp\factorio-build-gumsut\src\map\map.cpp (898): Map::setupEntities
c:\cygwin64\tmp\factorio-build-gumsut\src\scenario\scenario.cpp (220): Scenario::loadFactory
c:\cygwin64\tmp\factorio-build-gumsut\src\scenario\parallelscenarioloader.cpp (125): ParallelScenarioLoader::doLoad
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.12.25827\include\thr\xthread (232): std::_LaunchPad<std::unique_ptr<std::tuple<void (__cdecl*)(ParallelScenarioLoader * __ptr64,MapDeserialiser * __ptr64,enum InputType,InputHandler * __ptr64,MultiplayerManagerBase * __ptr64,bool),ParallelScenarioLoader * __ptr64,MapDeserialiser * __ptr64,enum InputType,InputHandler * __ptr64,MultiplayerManagerBase * __ptr64,bool>,std::default_delete<std::tuple<void (__cdecl*)(ParallelScenarioLoader * __ptr64,MapDeserialiser * __ptr64,enum InputType,InputHandler * __ptr64,MultiplayerManagerBase * __ptr64,bool),ParallelScenarioLoader * __ptr64,MapDeserialiser * __ptr64,enum InputType,InputHandler * __ptr64,MultiplayerManagerBase * __ptr64,bool> > > >::_Go
c:\program files (x86)\microsoft visual studio\2017\buildtools\vc\tools\msvc\14.12.25827\include\thr\xthread (211): std::_Pad::_Call_func
d:\th\minkernel\crts\ucrt\src\appcrt\startup\thread.cpp (115): thread_start<unsigned int (__cdecl*)(void * __ptr64)>
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFCF7017E94)
00007FFCF7017E94 (KERNEL32): (filename not available): BaseThreadInitThunk
ERROR: SymGetLineFromAddr64, GetLastError: 487 (Address: 00007FFCF7477AD1)
00007FFCF7477AD1 (ntdll): (filename not available): RtlUserThreadStart
Stack trace logging done
  43.163 Error RailSegment.cpp:154: Error when creating segment 209185, found rail (straight-rail on {473.0000000000, -995.0000000000}) already connected to segment 209176
Logger::writeStacktrace skipped.
  43.163 Error Util.cpp:67: Unexpected error occurred. If you're running the latest version of the game you can help us solve the problem by posting the contents of the log file on the Factorio forums.
Please also include the save file(s), any mods you may be using, and any steps you know of to reproduce the crash.
  44.580 Error CrashHandler.cpp:227: Heap validation: success.
  44.581 Creating crash dump.
  44.696 CrashDump success
`

It seems like that overlapping waterway is the problem. Is there a way I can remove it without loading my save or something? I've got backups but they're 3 hours old. T_T

**Comment by Fing3rz** [comment]
I went ahead and started re-building everything I lost. I imagine I'll be done by the time you see this. So far so good though. I've been careful not to overlap the waterways and so far everything is save/loading fine.

**Comment by squidy5** [comment]
damn, i am sorry for the extra work this caused you, will fix as fast as possible

**Comment by Fing3rz** [comment]
Hey, it's not a problem. Didn't mean to sound like I was complaining(lol). I appreciate the work you've put into the mod. It's a great mod. It allows for my biter free island base. hehe. Also everything seems to be working fine atm. Except the waterways don't show the blocks when placing signals on them. Not sure if that's working as intended or not. anyways, thx!
