### ISSUE TITLE
Making use of ships in LTN

### ISSUE THREAD

**Issue by 0ptera** [rudegrass/cargo_ships#14]
I've adopted LTN to work with your mod, however it'd be nice if you could fix some small visual glitches with ports and ships before I publish it.

Demo save:
Use with LTN development fork https://github.com/Yousei9/Logistic-Train-Network/tree/1.9.6
[_Testworld 0.16 - ltn port.zip](https://github.com/rudegrass/cargo_ships/files/2671249/_Testworld.0.16.-.ltn.port.zip)

- Port circuit connectors are floating around
![2018-12-12-10-36-11-3572680](https://user-images.githubusercontent.com/8436934/49860252-c2b31380-fdf9-11e8-820d-55be86a95c5d.png)

- Ship engine entities could use an unique icon.
![2018-12-12-10-34-10-6174572](https://user-images.githubusercontent.com/8436934/49860150-8089d200-fdf9-11e8-9093-53e141f7c845.png)
Wagon icons are only incorrect in the current release but are fine in the repository.

**Comment by squidy5** [comment]
I wont get to do this right away, i am pretty busy right now.

**Comment by 0ptera** [comment]
No problem, I'll try and get the connectors lined up with the top of the pole and send you a pull request.

**Comment by squidy5** [comment]
sweet, thank you! uploading now!
