### ISSUE TITLE
Crash when bridge opens.

### ISSUE THREAD

**Issue by numbernegative** [rudegrass/cargo_ships#20]
Was doing testing with the new bridges and am getting a crash every time it opens. The animation plays fine but as soon and the animation finishes I get this error and crash back to main menu:
![image](https://user-images.githubusercontent.com/11063321/52896113-cf9d0c00-3188-11e9-919e-6a7aa326e94e.png)
I have a lot of mods installed but here's the save it if helps you:
[Creative world.zip](https://github.com/rudegrass/cargo_ships/files/2871709/Creative.world.zip)

**Comment by squidy5** [comment]
i am having difficulties opening the save, and dont want to install all those mods :P.
does deleting and replacing the bridge change anything?

**Comment by numbernegative** [comment]
Oddly enough it went away with an update you pushed later that week.
feel free to mark as closed. I'll be moving to .17 soon enough and the mod list will be different.

**Comment by squidy5** [comment]
okay, great! i did change the bridge-logic a little in that update, so i might have fixed the issue accidently ;)
