### ISSUE TITLE
Wrong oilrig pollution

### ISSUE THREAD

**Issue by ZXQWAS** [rudegrass/cargo_ships#27]
Oil rigs do pollute the oceans indeed, but the amount of pollution I'm getting in this mod is closer to a sunken oil tanker.
https://i.imgur.com/BHR9EHD.png
Was it not adapted for the 0.17 pollution?

**Comment by squidy5** [comment]
What was the 0.17 change in pollution dynamics exactly? 
In general high rate of pollution is intended, to blance out the fact, that most off the pollution cloud will be ontop of water, and the oil rigs wont ever be attacked themselve. But i am willing to check if its exessive right now.

**Comment by ZXQWAS** [comment]
0.17.12
> Internal pollution values have been normalized, and they are now roughly 60 times less compared to what they were.

Everyone had to lower their modded pollution by 60 times. Also for dynamics, the pollution consumption was changed for all tiles in some later update, including being significantly lowered for water. The main problem is not in the cloud though, it's in the evolution. If you didn't change the pollution for 0.17, this means that 1 oil rig produces 60 times more evolution than it used to be.

**Comment by squidy5** [comment]
I see. wil be fixed when i find the time to do it.

**Comment by squidy5** [comment]
fixed in newest release
