### ISSUE TITLE
Waterways are extremely hard to see

### ISSUE THREAD

**Issue by mkaito** [rudegrass/cargo_ships#30]
I know the idea is that a waterway is just a fictional entity that must exist because ships are reskinned trains. However, the fact is that we need to build them. So we need to see them. Sometimes, quite clearly, like when making blueprints.

They are barely visible with the grid on, or in the blueprint window.

You could implement an option to tint them some other colour, and make the lines slightly thicker.

I presume you have the source file those those four dozen PNG :wink:

**Comment by squidy5** [comment]
actually i dont have a source file for those pngs, so all editing will have to be done manually (or with some kind of batch editing commands that i dont know) or just use the more visible versions this mod used to have. 
I will think about implementing an option for switching between those two versions, it wont be an ingame option though and require a restart off the game.

**Comment by squidy5** [comment]
i added a mod option to toggle waterway graphics
