### ISSUE TITLE
Crash with the Creative Mod when landfill ghosts on water get instantly constructed

### ISSUE THREAD

**Issue by 1avek1** [rudegrass/cargo_ships#32]
1057.704 Error MainLoop.cpp:1173: Exception at tick 57599: The mod Creative Mod caused a non-recoverable error.
Please report this error to the mod author.

Error while running event creative-mod::on_tick (ID 0)
The mod Cargo Ships caused a non-recoverable error.
Please report this error to the mod author.

Error while running event cargo-ships::on_robot_built_tile (ID 47)
__cargo-ships__/control.lua:95: attempt to index local 'surface' (a nil value)
stack traceback:
	__cargo-ships__/control.lua:95: in function <__cargo-ships__/control.lua:85>
stack traceback:
	__creative-mod__/scripts/util.lua:160: in function 'raise_event'
	__creative-mod__/scripts/util.lua:252: in function 'raise_event_for_revived_tile_ghosts'
	__creative-mod__/scripts/util.lua:283: in function 'revive_tile_ghost_and_raise_event'
	__creative-mod__/scripts/cheats.lua:2735: in function 'tick'
	__creative-mod__/scripts/events.lua:177: in function <__creative-mod__/scripts/events.lua:146>
stack traceback:
	[C]: in function 'raise_event'
	__creative-mod__/scripts/util.lua:160: in function 'raise_event'
	__creative-mod__/scripts/util.lua:252: in function 'raise_event_for_revived_tile_ghosts'
	__creative-mod__/scripts/util.lua:283: in function 'revive_tile_ghost_and_raise_event'
	__creative-mod__/scripts/cheats.lua:2735: in function 'tick'
	__creative-mod__/scripts/events.lua:177: in function <__creative-mod__/scripts/events.lua:146

**Comment by squidy5** [comment]
thanks for the report. the issue has already been fixed and a new version will be uploaded soon.
