### ISSUE TITLE
AII Vehicles Support: Hauler

### ISSUE THREAD

**Issue by Saevon** [rudegrass/cargo_ships#35]
The cargo ships are good early on, and being able to use them with AAI-vehicles would be fun (especially on a super-expensive map, where it takes a while before waterways)

Don't have my PC, or I'd make a pull-request... but heres how you do it
```lua
-- control.lua
remote.add_interface("cargo_ships", {
    hauler_types = function(data)
        return {
            'indep-boat',
        }
    end,
})
```

**Comment by squidy5** [comment]
hey! i never used aai vehicles, therfore i dont really now how to test this. have you tested this?

**Comment by Saevon** [comment]
Yeah, I have a personal mod that adds this, works fine.

P.S. if you added more boats that are supposed to work when not on a rail, you just add them to the table
