### ISSUE TITLE
Startup error due to bob's mods

### ISSUE THREAD

**Issue by adamcharnock** [rudegrass/cargo_ships#36]
I'm starting factorio for the first time in a few days (a week or two tops) and I'm seeing the following:

<img width="746" alt="Screenshot 2019-07-03 at 00 28 03" src="https://user-images.githubusercontent.com/138215/60553060-814c6c00-9d29-11e9-9483-961c321505b3.png">

Has bob's mods change something which has caused a breakage here?

---

Also, thank you so much for this mod. I love having ships!

**Comment by squidy5** [comment]
thanks for the report-
has been fixed in the last update.
