### ISSUE TITLE
Startup error - incomplete collision mask

### ISSUE THREAD

**Issue by ST-DDT** [rudegrass/cargo_ships#39]
![grafic](https://user-images.githubusercontent.com/1579362/68144619-5e7ad000-ff34-11e9-8e39-9db0a5ca0d32.png)

Broke after updating to Factorio 0.17.75
Affects Cargo-ships: 0.0.47

**Comment by stockmind** [comment]
See solution here:
https://mods.factorio.com/mod/cargo-ships/discussion/5dc08c283ef66f000ba2f1fb

```
In the water_rails.lua file in the prototypes folder (cargo ship mod) change the collision mask as shown here:

--bridge_crossing.collision_mask ={}
bridge_crossing.collision_mask ={"object-layer"}

and

--invisible_rail.collision_mask ={}
invisible_rail.collision_mask ={"object-layer"}
```

**Comment by OvermindDL1** [comment]
@stockmind Doesn't work on servers as clients sync from the mod portal and not from the server, thus they are still broken when attempting to join.

This is still an issue until the mod portal version is updates.

**Comment by stockmind** [comment]
Well, this fixes this issue, and credits go to people on those pages. Never said anything about the mod portal or servers :) I've already made a pull request #41 

Until it gets merged your clients need to patch their mods too.
On my server, my clients use a patched mod zip to get it working until it gets fixed here :)

**Comment by squidy5** [comment]
mod is updated now
