### ISSUE TITLE
(Factorio 17.79, mod 0.0.50) Mod crashes when building a ghost Lifting train bridge next to a rail

### ISSUE THREAD

**Issue by hharck** [rudegrass/cargo_ships#44]
When holding a Lifting train bridge green placement squares appear next to rail tracks:
![Screenshot 1](https://user-images.githubusercontent.com/15613999/80686551-27dbd780-8ac9-11ea-8b33-7f4ee7cad653.png)

If I try to build the Lifting train bridge on the rail track the game says "Bridges must be placed[...]", but if I build it as a ghost by shift clicking it will be placed:

![Screenshot 2](https://user-images.githubusercontent.com/15613999/80686569-2c07f500-8ac9-11ea-8241-efc763d2157c.png)

But as soon I turn on my personal roboport it will be build, and this :
![Screenshot 3](https://user-images.githubusercontent.com/15613999/80686573-2e6a4f00-8ac9-11ea-8675-c95a3ed8b38d.png)

Other mods active: Auto Deconstruct

**Comment by squidy5** [comment]
thanks for the detailed bug report. fixed for the latest release (only for factorio > 18.0 though)
