### ISSUE TITLE
(Factorio 17.79, mod 0.0.50) Game crashes when placing landfill under a "Lifting train bridge"

### ISSUE THREAD

**Issue by hharck** [rudegrass/cargo_ships#45]
When placing (Vanilla) landfill near or under a Lifting train bridge this happens:

![Screenshot](https://user-images.githubusercontent.com/15613999/80687216-41315380-8aca-11ea-8b18-5913eacd5ee5.png)

It may be a conflict with the CanalBuilder mod, since the shallow water below the bridge was created by the CanalBuilder mod (Ver. 17.6).

This crash happened while researching [this issue](https://github.com/rudegrass/cargo_ships/issues/44)

**Comment by squidy5** [comment]
thanks for the report! fixed for the newest version.
