### ISSUE TITLE
local choices = require("choices")

### ISSUE THREAD

**Issue by Matthodric** [rudegrass/cargo_ships#49]
When Starting a (multiplayer) game, I received an error about some local choices in the "[control.lua](https://github.com/rudegrass/cargo_ships/blob/master/control.lua)" Old version worked fine so I checked to see what had changed and found you had removed it from [settings.lua](https://github.com/rudegrass/cargo_ships/blob/master/settings.lua) but must have forgot to remove it in the [control.lua](https://github.com/rudegrass/cargo_ships/blob/master/control.lua), so I commented it out and now it works. 

```lua 
1 require("logic.ship_placement")
2 require("logic.oil_placement")
3 require("logic.long_reach")
4 require("logic.bridge_logic")
5 require("logic.pump_placement")
6 require("logic.blueprint_logic")
7 require("gui.oil_rig_gui")
8 --require("logic.crane_logic")
9 require("logic.rolling_stock_logic")
10 --local choices = require("choices")
```

**Comment by squidy5** [comment]
version 55 on the mod portal did not include the problem, i did delete the line causing the issue before making the relase. but i didnt update the git, did you get the mod directly from the repository by any chance?

**Comment by Matthodric** [comment]
Yeah, I always download mods from github if possible to avoid auto updates and other nonsense.
