### ISSUE TITLE
rail waterway networks are interconactable

### ISSUE THREAD

**Issue by L0ric0** [rudegrass/cargo_ships#56]
It is possible to build a rail up to the edge of the water and from there build a waterway. the both entitys will connect and it is possible to ride a ship (which has to be placed on water) onto land and a train onto water.

**Comment by squidy5** [comment]
true. 
this behavior arises from the base games limitations (there really only is one type of rails)
the solution would be to check after every placed rail if an "illeagal" situation of this kind has arisen by the addition of this rail piece.
which i was/am too lazy to do.
