### ISSUE TITLE
buoy graphics are not on the entity

### ISSUE THREAD

**Issue by L0ric0** [rudegrass/cargo_ships#57]
buoy graphics are displaced from the entity. This is probably done so that they do not intersect with the ships driving on waterways, but this creates problems when deconstructing them or manually driving a ship, as one can ram a buoy when one does not see one.

**Comment by squidy5** [comment]
true. there are game limitations that keep me from moving the entity further away, and buoys not clipping into the ships graphics was the more important issue for me...
