### ISSUE TITLE
buoys can be destroyed by driving over them with a ship

### ISSUE THREAD

**Issue by L0ric0** [rudegrass/cargo_ships#58]
this is not realy a bug but personal preference. As it is easy to drive over buoys and they are realy fragile and ships having a realy long breake way it is prity anoying having to replace them when one runs one over. would it be possible to make them indestructible or minimise the colision box of the buoys

**Comment by squidy5** [comment]
could make them indestructible. i am not really maintaining this mod currently, but if anybody wants to push a pull request i will merge.
