### ISSUE TITLE
reach to destruct waterways etc. is the normal size

### ISSUE THREAD

**Issue by L0ric0** [rudegrass/cargo_ships#59]
it would be nice if the reach to destruct waterways and so on would be as large as the construction reach, as precisly navigating ships to remove waterways is a real hassal

**Comment by squidy5** [comment]
hi. sorry, i havent been active on this project.
to your request:
the players reach can (as far as i understand) not be modified as a function of what you are doing but is a constant value.
this mod changes this value whenever you equip a waterway, but there is no way to detect what entity you want to delete beforehand and change the value accordingly.
A practical solution: equip waterways when deleting other waterways, this will increase your reach accordingly.
