### ISSUE TITLE
missing deep sea oil with factorio world mod 

### ISSUE THREAD

**Issue by squidy5** [rudegrass/cargo_ships#7]
mods that change terrain(water?) generation like factorio world result in no deap sea oil being placed

**Comment by ArcaniVictus** [comment]
You have to add Factorio World as a dependent for Cargo Ships. This forces Cargo ships to load after Factorio World and it fixes the issues with deep sea oil's spawn data being overridden by Factorio World.

This can be done very easily.
- Open Cargo Ships zipped folder with Winrar or 7zip (Doesn't have to be unzipped). 
- Then open, info.json.
- Highlight the entire line, "dependencies", and replace it with: 
"dependencies": ["base >= 0.16", "factorio-world >= 0.16.1"],
- Save the file and close Winrar or 7zip. Accept any popup confirming the edit.
- Install mod as normal and enjoy!

Once edited info.json should look exactly as below:
{
"name": "cargo-ships",
"version": "0.0.16",
"title": "Cargo Ships",
"author": "rude_grass",
"description": "Adds cargo ships, oil tankers and deep sea oil rigs",
"dependencies": ["base >= 0.16", "factorio-world >= 0.16.1"],
"factorio_version": "0.16"
}

**Comment by squidy5** [comment]
thanks!
