### ISSUE TITLE
Compatibility with Noxy's Swimming

### ISSUE THREAD

**Issue by robot256** [rudegrass/cargo_ships#82]
https://mods.factorio.com/mod/cargo-ships/discussion/60d8aa02034da71718abd648
This probably needs a pull request on their side to differentiate between boats and non-boats.

**Comment by snouz** [comment]
Could be pull requested on Noxy's repo directly

https://github.com/NoxyNixie/Noxys_Swimming/pulls

**Comment by robot256** [comment]
Fixed in release 0.1.14: https://github.com/rudegrass/cargo_ships/pull/101/commits/57da9cd19c72b0486f14a868bdd6f8c6d888eba1

`indep-boat` will not be affected by changes to tile friction modifiers.  Noxy still has to add code on their end to remove the extra splash effects around players riding in boats and ships.
