### ISSUE TITLE
Krastorio 2 compatibility: making deep oil "finite"

### ISSUE THREAD

**Issue by snouz** [rudegrass/cargo_ships#83]
Krastorio 2 uses oil that is not infinite and has a set amount of oil per node while oil nodes found in water are standard vanilla % system.

https://mods.factorio.com/mod/cargo-ships/discussion/5e74436cde88d4000caee962

**Comment by robot256** [comment]
Krastorio2 also changes the selection box of deep_oil to 1x1, and deep_oil doesn't reflect the change in map color of crude-oil.

**Comment by robot256** [comment]
Fixed in #94.  Beware using the offshore oil richness bonus setting!
