### ISSUE TITLE
Krastorio 2 compatibility: adding k2's fuel to accepted boat fuel

### ISSUE THREAD

**Issue by snouz** [rudegrass/cargo_ships#85]
Haven't tested, but apparently, K2's fuel can't be used in ships.

**Comment by robot256** [comment]
Fixed in #94, assuming it's okay for ships to accept chemical & vehicle fuel, and boats to accept only vehicle fuel.

**Comment by GeneralTanker** [comment]
Also another modder has done done some compatibility between this mod and K2. The includes some material changes to include K2 resources in Cargo ship items. Would it be possible to add those as well.

https://mods.factorio.com/mod/krastorio-2-compat

**Comment by robot256** [comment]
How do other mods typically handle K2 compatibility for recipes?  In their mod, in K2, or in a third compatibility mod?  Just trying to judge how much we should put in here versus letting people download that other mod (and if their changes are "correct").

**Comment by GeneralTanker** [comment]
> How do other mods typically handle K2 compatibility for recipes? In their mod, in K2, or in a third compatibility mod? Just trying to judge how much we should put in here versus letting people download that other mod (and if their changes are "correct").

It's been a bit of all three with a few cases of the other mod or K2 including the compatibility afterwards. Extra compatibility mods are used if the mod author doesn't bother to add compatibility. The main things the third party mod has that has not been included is the addition of K2 ingredients to cargo ships items (steel gears and steel beams). Another mod adds the K2 vehicle grids to the ships (train grid for the cargo and tanker ship and car grid for the boat).  Those would be the two other things add to improve compatibility.
