### ISSUE TITLE
Latest mod breaks mining drills and map generation

### ISSUE THREAD

**Issue by rherrick** [rudegrass/cargo_ships#87]
I made a screen recording of these issues, which you can find [here](https://youtu.be/tFcNRxM2A8I).

Demonstrates two bugs I ran into in the latest version of the cargo_ships mod.

The first bit shows base Factorio, no mods active, start of game, setting up a mining drill and accessing it to add fuel.

I then quit that game, activated the cargo_ships mod, restarted, and started a new game. This time when I set up the mining drill I couldn't access it to add fuel.

I quit that game and started another new game, this time changing the map settings but still ended up with the same map I had in the last game.

This is the latest non-beta version of Factorio, 1.1.48 (build 59155, mac), running on a MacBook Pro (Retina, 15-inch, Mid 2015), OS X 11.6.1, but I actually discovered the bugs running on my 27" iMac (also 11.6.1).

Let me know if I can provide any other info to help solve the issue.

**Comment by snouz** [comment]
Hi, thank you so much for the report (and the thorough video), I've forwarded that to the specialist (@robot256 who actually changed that bit)

**Comment by Mocha-Not-Latte** [comment]
> Hi, thank you so much for the report (and the thorough video), I've forwarded that to the specialist (@robot256 who actually changed that bit)

The issue might be the ore collision layers from PR #78

**Comment by robot256** [comment]
In your video I see you are using cargo ships 0.1.0.  Can you please try it with the latest 0.1.4?

**Comment by robot256** [comment]
I fixed the issue by setting the land ores to have `selection-priority=49` instead of the default of 50.  Should be released soon.
