### ISSUE TITLE
connecting to track

### ISSUE THREAD

**Issue by ChuckSavage** [rudegrass/cargo_ships#92]
I'm in the middle of a playthrough, and upgraded to the latest version 1.6(?), and now cannot use my blueprints that connect to the bulk rail loaders, and other track. I see you added protection vs track connections, can you make that a toggle in the map settings please.

**Comment by snouz** [comment]
Hi, thanks for the report ! It's been added to 0.1.7 as a runtime setting. Cheers!

**Comment by ChuckSavage** [comment]
Thanks for getting right on this. I'll test it tonight.

PS If you're interested in seeing this in action, I stream at twitch.tv/dune__
