### ISSUE TITLE
[1.7] sometimes water ways don't show up on map

### ISSUE THREAD

**Issue by ChuckSavage** [rudegrass/cargo_ships#95]
blue printed and built with bots does show on map, but manually drawn not

**Comment by ChuckSavage** [comment]
edit: only old blue prints of water ways show up on map. New blue prints of new water ways don't either.

**Comment by ChuckSavage** [comment]
more info - sometimes old blue printed water ways don't show up either.

**Comment by robot256** [comment]
Can you please post your mod list?  Any "cheat mode" mods, or running in editor mode?  It sounds like something is building or reviving waterways without raising the events we're expecting.

**Comment by snouz** [comment]
Or even better, could you post your save ? thanks for the report BTW : )

**Comment by ChuckSavage** [comment]
Here's the save - https://www.dropbox.com/s/3vcuq5cz658urch/Islands%20001%20036.zip?dl=0

Look up in the far north west, that's where the newest water ways were placed. You can see the different views, of some can be seen from map (from blueprints made in 0.59) but not all. Some blueprints made in 0.59 still don't show up in map view either. All waterways built by hand don't show up in map view. That's the only one I can duplicate 100% of the time. The blue prints are inconsistent. If they show up, they always show up, and if they don't, they don't.

You can also see my vod on twitch. Check it out starting 37 minutes in for when I first discover this issue - https://www.twitch.tv/videos/1224717794?t=00h37m20s

**Comment by robot256** [comment]
I figured it out.  Disabling the "Prevent connections between waterways and rails" option completely disabled the waterway replacement logic.  Will be fixed in the next release, along with a migration patch to fix existing un-replaced rails.

**Comment by snouz** [comment]
This is now fixed in 0.1.8
