### ISSUE TITLE
[1.8] LTN ports don't show connections for pumps

### ISSUE THREAD

**Issue by ChuckSavage** [rudegrass/cargo_ships#98]
Unlike the regular ports that have green squares on either side for pump connections, the LTN ports don't.

**Comment by snouz** [comment]
Thanks for the report ! I found the issue, which is the fact that LTN is copying the port prototype, but not the logic of the pump placement (the pump placement code only checks for the normal port prototype)

Anyway, it'll be fixed in the next one !
